### `Merge()` And `Joins()`

In [1]:
import pandas as pd

In [2]:
Restaurant = pd.DataFrame(
    {
        'restaurant_id':['R001', 'R002', 'R003', 'R004', 'R005', 'NaN', 'R007'],
        'restaurant_name':['Dominos Pizza', 'KFC', 'McDonalds', 'Pizza Hut', 'Subway', 'Unknown Restaurant', 'Taco Bell'],
        'cuisine_type':['Italian', 'American', 'Fast Food', 'Italian', 'Fast Food', 'NaN', 'Mexican'],
        'rating':[4.2, 4.0, 3.8, 4.1, 4.3, 3.5, 4.0]
    }
)
Restaurant

  restaurant_id     restaurant_name cuisine_type  rating
0          R001       Dominos Pizza      Italian     4.2
1          R002                 KFC     American     4.0
2          R003           McDonalds    Fast Food     3.8
3          R004           Pizza Hut      Italian     4.1
4          R005              Subway    Fast Food     4.3
5           NaN  Unknown Restaurant          NaN     3.5
6          R007           Taco Bell      Mexican     4.0

In [3]:
Order = pd.DataFrame(
    {
        'order_id':['0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009'],
        'restaurant_id':['R001', 'R002', 'NaN', 'R001', 'R005', 'NaN', 'R007', 'R999', 'R004'],
        'customer_name':['Rahul', 'Priya', 'Amit', 'Sneha', 'Rohan', 'Kavya', 'Arjun', 'Pooja', 'Vikash'],
        'order_amount':[450.0, 320.0, 280.0, 520.0, 'NaN', 380.0, 420.0, 150.0, 350.0],
        'order_date':['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20', '2024-01-21', '2024-01-22', '2024-01-23']
        
    }
)
Order

  order_id restaurant_id customer_name order_amount  order_date
0     0001          R001         Rahul        450.0  2024-01-15
1     0002          R002         Priya        320.0  2024-01-16
2     0003           NaN          Amit        280.0  2024-01-17
3     0004          R001         Sneha        520.0  2024-01-18
4     0005          R005         Rohan          NaN  2024-01-19
5     0006           NaN         Kavya        380.0  2024-01-20
6     0007          R007         Arjun        420.0  2024-01-21
7     0008          R999         Pooja        150.0  2024-01-22
8     0009          R004        Vikash        350.0  2024-01-23

### `Inner Join`

In [4]:
df = pd.merge(Restaurant, Order, on ='restaurant_id', how = "inner")
df

,restaurant_id,restaurant_name,cuisine_type,rating,order_id,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,Rahul,450.0,2024-01-15
1,R001,Dominos Pizza,Italian,4.2,0004,Sneha,520.0,2024-01-18
2,R002,KFC,American,4.0,0002,Priya,320.0,2024-01-16
3,R004,Pizza Hut,Italian,4.1,0009,Vikash,350.0,2024-01-23
4,R005,Subway,Fast Food,4.3,0005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0003,Amit,280.0,2024-01-17
6,NaN,Unknown Restaurant,NaN,3.5,0006,Kavya,380.0,2024-01-20
7,R007,Taco Bell,Mexican,4.0,0007,Arjun,420.0,2024-01-21

### `Left Join`

In [5]:
df1 = pd.merge(Restaurant, Order, on ='restaurant_id', how = "left")
df1

,restaurant_id,restaurant_name,cuisine_type,rating,order_id,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,Rahul,450.0,2024-01-15
1,R001,Dominos Pizza,Italian,4.2,0004,Sneha,520.0,2024-01-18
2,R002,KFC,American,4.0,0002,Priya,320.0,2024-01-16
3,R003,McDonalds,Fast Food,3.8,NaN,NaN,NaN,NaN
4,R004,Pizza Hut,Italian,4.1,0009,Vikash,350.0,2024-01-23
5,R005,Subway,Fast Food,4.3,0005,Rohan,NaN,2024-01-19
6,NaN,Unknown Restaurant,NaN,3.5,0003,Amit,280.0,2024-01-17
7,NaN,Unknown Restaurant,NaN,3.5,0006,Kavya,380.0,2024-01-20
8,R007,Taco Bell,Mexican,4.0,0007,Arjun,420.0,2024-01-21

### `Right Join`

In [6]:
df2 = pd.merge(Restaurant, Order, on ='restaurant_id', how = "right")
df2

,restaurant_id,restaurant_name,cuisine_type,rating,order_id,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,Rahul,450.0,2024-01-15
1,R002,KFC,American,4.0,0002,Priya,320.0,2024-01-16
2,NaN,Unknown Restaurant,NaN,3.5,0003,Amit,280.0,2024-01-17
3,R001,Dominos Pizza,Italian,4.2,0004,Sneha,520.0,2024-01-18
4,R005,Subway,Fast Food,4.3,0005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0006,Kavya,380.0,2024-01-20
6,R007,Taco Bell,Mexican,4.0,0007,Arjun,420.0,2024-01-21
7,R999,NaN,NaN,NaN,0008,Pooja,150.0,2024-01-22
8,R004,Pizza Hut,Italian,4.1,0009,Vikash,350.0,2024-01-23

### `Outer Join`

In [7]:
df3 = pd.merge(Restaurant, Order, on ='restaurant_id', how = "outer")
df3.head()

,restaurant_id,restaurant_name,cuisine_type,rating,order_id,customer_name,order_amount,order_date
0,NaN,Unknown Restaurant,NaN,3.5,0003,Amit,280.0,2024-01-17
1,NaN,Unknown Restaurant,NaN,3.5,0006,Kavya,380.0,2024-01-20
2,R001,Dominos Pizza,Italian,4.2,0001,Rahul,450.0,2024-01-15
3,R001,Dominos Pizza,Italian,4.2,0004,Sneha,520.0,2024-01-18
4,R002,KFC,American,4.0,0002,Priya,320.0,2024-01-16

## Merge Data Base on index 

`Join()`

In [8]:
df4 = pd.merge(Restaurant, Order, left_index=True,right_index=True,how='inner')
df4

,restaurant_id_x,restaurant_name,cuisine_type,rating,order_id,restaurant_id_y,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,R001,Rahul,450.0,2024-01-15
1,R002,KFC,American,4.0,0002,R002,Priya,320.0,2024-01-16
2,R003,McDonalds,Fast Food,3.8,0003,NaN,Amit,280.0,2024-01-17
3,R004,Pizza Hut,Italian,4.1,0004,R001,Sneha,520.0,2024-01-18
4,R005,Subway,Fast Food,4.3,0005,R005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0006,NaN,Kavya,380.0,2024-01-20
6,R007,Taco Bell,Mexican,4.0,0007,R007,Arjun,420.0,2024-01-21

In [9]:
df4 = pd.merge(Restaurant, Order, left_index=True,right_index=True,how='inner', suffixes=('_R','_O'))
df4

,restaurant_id_R,restaurant_name,cuisine_type,rating,order_id,restaurant_id_O,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,R001,Rahul,450.0,2024-01-15
1,R002,KFC,American,4.0,0002,R002,Priya,320.0,2024-01-16
2,R003,McDonalds,Fast Food,3.8,0003,NaN,Amit,280.0,2024-01-17
3,R004,Pizza Hut,Italian,4.1,0004,R001,Sneha,520.0,2024-01-18
4,R005,Subway,Fast Food,4.3,0005,R005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0006,NaN,Kavya,380.0,2024-01-20
6,R007,Taco Bell,Mexican,4.0,0007,R007,Arjun,420.0,2024-01-21

In [10]:
df5 = pd.merge(Restaurant, Order, left_index=True,right_index=True,how='left', suffixes=('_R','_O'))
df5

,restaurant_id_R,restaurant_name,cuisine_type,rating,order_id,restaurant_id_O,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,R001,Rahul,450.0,2024-01-15
1,R002,KFC,American,4.0,0002,R002,Priya,320.0,2024-01-16
2,R003,McDonalds,Fast Food,3.8,0003,NaN,Amit,280.0,2024-01-17
3,R004,Pizza Hut,Italian,4.1,0004,R001,Sneha,520.0,2024-01-18
4,R005,Subway,Fast Food,4.3,0005,R005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0006,NaN,Kavya,380.0,2024-01-20
6,R007,Taco Bell,Mexican,4.0,0007,R007,Arjun,420.0,2024-01-21

In [11]:
df6 = pd.merge(Restaurant, Order, left_index=True,right_index=True,how='right', suffixes=('_R','_O'))
df6

,restaurant_id_R,restaurant_name,cuisine_type,rating,order_id,restaurant_id_O,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,R001,Rahul,450.0,2024-01-15
1,R002,KFC,American,4.0,0002,R002,Priya,320.0,2024-01-16
2,R003,McDonalds,Fast Food,3.8,0003,NaN,Amit,280.0,2024-01-17
3,R004,Pizza Hut,Italian,4.1,0004,R001,Sneha,520.0,2024-01-18
4,R005,Subway,Fast Food,4.3,0005,R005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0006,NaN,Kavya,380.0,2024-01-20
6,R007,Taco Bell,Mexican,4.0,0007,R007,Arjun,420.0,2024-01-21
7,NaN,NaN,NaN,NaN,0008,R999,Pooja,150.0,2024-01-22
8,NaN,NaN,NaN,NaN,0009,R004,Vikash,350.0,2024-01-23

In [12]:
df7 = pd.merge(Restaurant, Order, left_index=True,right_index=True,how='outer', suffixes=('_R','_O'))
df7

,restaurant_id_R,restaurant_name,cuisine_type,rating,order_id,restaurant_id_O,customer_name,order_amount,order_date
0,R001,Dominos Pizza,Italian,4.2,0001,R001,Rahul,450.0,2024-01-15
1,R002,KFC,American,4.0,0002,R002,Priya,320.0,2024-01-16
2,R003,McDonalds,Fast Food,3.8,0003,NaN,Amit,280.0,2024-01-17
3,R004,Pizza Hut,Italian,4.1,0004,R001,Sneha,520.0,2024-01-18
4,R005,Subway,Fast Food,4.3,0005,R005,Rohan,NaN,2024-01-19
5,NaN,Unknown Restaurant,NaN,3.5,0006,NaN,Kavya,380.0,2024-01-20
6,R007,Taco Bell,Mexican,4.0,0007,R007,Arjun,420.0,2024-01-21
7,NaN,NaN,NaN,NaN,0008,R999,Pooja,150.0,2024-01-22
8,NaN,NaN,NaN,NaN,0009,R004,Vikash,350.0,2024-01-23

### . `concat()`  Data Stacking

In [13]:
Data1 = pd.DataFrame({
    'ID' : [1,2,3,4,5],
    'Name':['Amit', 'Bina', 'Chetan', 'Deepa', 'Esha'],
    'Age' :[21,22,23,21,24],
    'Score':[85,90,88,92,95]
})

Data1

   ID    Name  Age  Score
0   1    Amit   21     85
1   2    Bina   22     90
2   3  Chetan   23     88
3   4   Deepa   21     92
4   5    Esha   24     95

In [14]:
Data2 = pd.DataFrame({
    'ID' : [6,7,8,9,10,11,12],
    'Name':['Farahan', 'Ved', 'Ayush', 'Hemant', 'Ravi', 'Raju', 'Ankur'],
    'Age':[23,22,21,24,25,23,22],
    'Score':[87,91,85,89,93,90,88],
    'City' :['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Goa', 'Chennai', 'Pune']
})

Data2

   ID     Name  Age  Score     City
0   6  Farahan   23     87    Delhi
1   7      Ved   22     91   Mumbai
2   8    Ayush   21     85     Pune
3   9   Hemant   24     89    Delhi
4  10     Ravi   25     93      Goa
5  11     Raju   23     90  Chennai
6  12    Ankur   22     88     Pune

### Verticle Stacking

In [15]:
df8 = pd.concat([Data1, Data2], axis =0, ignore_index = True)
df8

    ID     Name  Age  Score     City
0    1     Amit   21     85      NaN
1    2     Bina   22     90      NaN
2    3   Chetan   23     88      NaN
3    4    Deepa   21     92      NaN
4    5     Esha   24     95      NaN
5    6  Farahan   23     87    Delhi
6    7      Ved   22     91   Mumbai
7    8    Ayush   21     85     Pune
8    9   Hemant   24     89    Delhi
9   10     Ravi   25     93      Goa
10  11     Raju   23     90  Chennai
11  12    Ankur   22     88     Pune

### Horizontal Stacking

In [16]:
df9 = pd.concat([Data1, Data2], axis =1)
df9

    ID    Name   Age  Score  ID     Name  Age  Score     City
0  1.0    Amit  21.0   85.0   6  Farahan   23     87    Delhi
1  2.0    Bina  22.0   90.0   7      Ved   22     91   Mumbai
2  3.0  Chetan  23.0   88.0   8    Ayush   21     85     Pune
3  4.0   Deepa  21.0   92.0   9   Hemant   24     89    Delhi
4  5.0    Esha  24.0   95.0  10     Ravi   25     93      Goa
5  NaN     NaN   NaN    NaN  11     Raju   23     90  Chennai
6  NaN     NaN   NaN    NaN  12    Ankur   22     88     Pune